version: '3'
services:
    dynamodb:
        image: dwmkerr/dynamodb
        ports:
            - "8000:8000"
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - dynamodb
        environment:
            - AWS_ACCESS_KEY_ID=your_access_key_id
            - AWS_SECRET_ACCESS_KEY=your_secret_access_key

